# Generated by Django 4.1.4 on 2022-12-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(default='Категория', max_length=50, verbose_name='Категория'),
        ),
    ]
